---
    pid_file : /tmp/fos-linux.pid
    zlocator : tcp/127.0.0.1:7447
    zfilelocator: unixsock-stream//tmp/zenoh.sock
    path : /etc/fos/linux-network
    run_path : /var/fos/linux-network
    monitoring_interveal: 10
    overlay_iface : ens2
    dataplane_iface: ens2